mission_node:
  ros__parameters:
    tracked_topic: /tracking/targets
    parcel_track_topic: /tracking/parcel_tracks
    mission_topic: /mission/target
    mission_state_topic: /mission/state
    parcel_info_topic: /mission/parcel_info
    color_pickup_values: ["green", "yellow"]
    color_dropoff_values: ["blue", "red"]
    prefer_identified_parcels: true
    parcel_timeout_sec: 3.0
    state_hold_sec: 1.0

    # Nowy parametr: plik definiujący scenariusz FSM.
    # Jeżeli ścieżka jest pusta, node użyje scenariusza wbudowanego.
    scenario_file: src/g1_light_tracking/config/mission_scenario_default.yaml
    
