mission_node:
  ros__parameters:
    tracked_topic: /tracking/targets
    parcel_track_topic: /tracking/parcel_tracks
    mission_topic: /mission/target
    parcel_info_topic: /mission/parcel_info
    binding_topic: /tracking/parcel_bindings
    color_pickup_values: ["green", "yellow"]
    color_dropoff_values: ["blue", "red"]
    prefer_identified_parcels: true
    parcel_timeout_sec: 3.0
