builtin_interfaces/Time stamp
string frame_id

string state
string previous_state
string reason

string active_parcel_box_track_id
string active_shipment_id
bool has_active_parcel
bool has_drop_target
bool is_terminal

string track_id
string parcel_box_track_id
string qr_track_id

string shipment_id
string pickup_zone
string dropoff_zone
string parcel_type
float32 mass_kg
string raw_payload

bool has_qr
string logistics_state
bool is_confirmed
float32 confidence

string active_target_type
string active_target_mode
