builtin_interfaces/Time stamp
string frame_id

string track_id
string target_type
string class_name
float32 confidence

geometry_msgs/Point position
geometry_msgs/Vector3 dimensions

float32 center_u
float32 center_v
float32 x_min
float32 y_min
float32 x_max
float32 y_max

string parcel_box_track_id
string qr_track_id
string shipment_id
string pickup_zone
string dropoff_zone
string parcel_type
float32 mass_kg
string raw_payload
bool has_qr
string logistics_state
bool is_confirmed

string color_label
string payload
string source_method
float32 age_sec
int32 missed_frames
